title: Md. Eftakharul Islam
description: Studnet 
baseurl: "/remple/"
url: ""
resume_url: "resume.pdf"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  
